### PR TITLE
feat: Enable NPM publishing

### PR DESCRIPTION
**Pull request by zharinov**
## Documentation (please check one with an [x])

- [ ] I have updated the documentation, or
- [ ] No documentation update is required

## How I've tested my work (please tick one)

I have verified these changes via:

- [ ] Code inspection only, or
- [ ] Newly added/modified unit tests

### CODE REVIEW

**Comment by rarkins** [comment]
Is there a semantic release step?

**Comment by zharinov** [comment]
My reasoning was to move quick until `0.1.x` versions, making `0.0.x` releases comsumable from Renovate as easy as simple version bump here in `package.json`.  Eventually I want to be more disciplined about library release cycle, once its API seems to be stable.

**Comment by rarkins** [comment]
What happens if you push a commit to main branch without bumping the package.json version - will the workflow just try to publish and then fail?

**Comment by zharinov** [comment]
No, it bypasses further steps because of negative conditional result. For example, recent commit did not bump any version: https://github.com/renovatebot/parser-utils/runs/3678592099?check_suite_focus=true

**Pull request merged**
